# Generated by Django 5.1.2 on 2025-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("author", models.CharField(max_length=100)),
                ("excerpt", models.TextField()),
                ("body", models.TextField()),
                ("tags", models.CharField(max_length=200)),
                ("featured_image", models.ImageField(upload_to="blog_images/")),
                ("publish_date", models.DateField()),
                ("seo_meta_title", models.CharField(max_length=200)),
                ("seo_description", models.TextField()),
            ],
        ),
    ]
