# Generated by Django 5.2.1 on 2026-01-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarregistration",
            name="attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webinarregistration",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
