# Generated by Django 5.2.1 on 2026-01-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_webinarregistration_attended_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinarregistration",
            old_name="state",
            new_name="city",
        ),
    ]
