# Generated by Django 5.2.1 on 2026-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_state_webinarregistration_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeathonRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "participation_type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Team", "Team")],
                        max_length=20,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=200, null=True)),
                ("idea_title", models.CharField(max_length=255)),
                ("focus_areas", models.JSONField(default=list)),
                ("idea_description", models.TextField()),
                (
                    "pitch_deck",
                    models.FileField(blank=True, null=True, upload_to="pitch_decks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
